select a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.TOTAL * b.PRICE) AS TOTAL_SALES
from BOOK b
JOIN (select BOOK_ID, SUM(SALES) as TOTAL
      from BOOK_SALES
      WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
      GROUP BY BOOK_ID
      ) s on s.BOOK_ID = b.BOOK_ID 
JOIN AUTHOR a on a.AUTHOR_ID = b.AUTHOR_ID
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
