-- 코드를 작성해주세요

SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
INNER JOIN ITEM_TREE t ON t.ITEM_ID = i.ITEM_ID
WHERE I.item_id NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY i.ITEM_ID DESC;