WITH FILTERED_RENTAL_HISTORY AS (
SELECT CAR_ID, MIN(START_DATE) AS START_DATE, MAX(END_DATE) AS END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
),
FILTERED_RENTAL_PLAN AS (
SELECT CAR_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '30일 이상')

SELECT c.CAR_ID, c.CAR_TYPE, ROUND((((100 - p.DISCOUNT_RATE) / 100) * c.DAILY_FEE * 30), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN FILTERED_RENTAL_HISTORY f ON c.CAR_ID = f.CAR_ID
INNER JOIN FILTERED_RENTAL_PLAN p ON p.CAR_TYPE = c.CAR_TYPE
WHERE (c.CAR_TYPE = '세단' OR c.CAR_TYPE = 'SUV')
AND (f.START_DATE > '2022-11-30' OR f.END_DATE < '2022-11-01' OR f.START_DATE IS NULL)
AND (((100 - p.DISCOUNT_RATE) / 100) * c.DAILY_FEE * 30 BETWEEN 500000 AND 1999999)
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;