SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i 
INNER JOIN ANIMAL_OUTS o ON o.ANIMAL_ID = i.ANIMAL_ID AND (o.SEX_UPON_OUTCOME LIKE '%Neutered%' OR o.SEX_UPON_OUTCOME LIKE '%Spayed%')
WHERE i.SEX_UPON_INTAKE LIKE '%Intact%'
ORDER BY i.ANIMAL_ID ASC;