SELECT YEAR(F.DIFFERENTIATION_DATE) AS YEAR, (M.SIZE_OF_COLONY - F.SIZE_OF_COLONY) AS YEAR_DEV, F.ID
FROM ECOLI_DATA F
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M ON M.YEAR = YEAR(F.DIFFERENTIATION_DATE) 
ORDER BY YEAR ASC, YEAR_DEV ASC;