-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND MONTH(DATE_OF_BIRTH) = 3  AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;

-- DATE_FORMAT(컬럼이름, '%Y-%m') 이런 식으로 변환할 수 있다.
-- 또한 MONTH()로 달을 추출할 수 있다. (이 외에 YEAR, DAY 등이 있음)