SELECT COUNT(f.FISH_TYPE) AS FISH_COUNT, n.FISH_NAME
FROM FISH_INFO f
INNER JOIN FISH_NAME_INFO n
ON f.FISH_TYPE = n.FISH_TYPE
GROUP BY n.FISH_NAME
ORDER BY FISH_COUNT DESC;

-- ORDER BY 할 때 별명으로 해도 됨.