SELECT info.ID, name.FISH_NAME, info.LENGTH
FROM FISH_INFO info
INNER JOIN FISH_NAME_INFO name ON name.FISH_TYPE = info.FISH_TYPE
WHERE info.LENGTH IS NOT NULL 
AND info.LENGTH = (
    SELECT MAX(sub.LENGTH)
    FROM FISH_INFO sub
    WHERE sub.FISH_TYPE = info.FISH_TYPE
)
ORDER BY info.ID ASC;