WITH SCORE_SUM AS (
SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO),
MAX_SCORE AS (
SELECT MAX(SCORE) AS MAX_SCORE
    FROM SCORE_SUM
)
SELECT S.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM SCORE_SUM S
JOIN HR_EMPLOYEES E ON E.EMP_NO = S.EMP_NO
JOIN MAX_SCORE M ON M.MAX_SCORE = S.SCORE;

    


